-- ============================================
-- LevelUP Backend - Script de inicializacion
-- Base de datos: lvlup_db (PostgreSQL 16)
-- Schema: public
-- ============================================
-- Generado a partir de 11 entidades JPA de 5 microservicios:
--   authService  (2): auth_sessions, usuarios
--   userService  (2): usuarios (compartida), direcciones
--   productService (3): products, product_specifications, resenas
--   cartService  (2): carts, cart_items
--   orderService (2): orders, order_items
--
-- ADVERTENCIA: Este script elimina y recrea TODAS las tablas.
-- Si hay datos en produccion, se perderan al ejecutar los DROP.
-- ============================================

-- Desactivar checks de FK durante drops
SET session_replication_role = 'replica';

-- ============================================
-- DROP TABLES (orden inverso por dependencias)
-- ============================================
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS carts CASCADE;
DROP TABLE IF EXISTS resenas CASCADE;
DROP TABLE IF EXISTS product_specifications CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS direcciones CASCADE;
DROP TABLE IF EXISTS auth_sessions CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;

-- Reactivar checks de FK
SET session_replication_role = 'origin';

-- ============================================
-- AUTH SERVICE + USER SERVICE (tabla compartida)
-- ============================================
-- La tabla "usuarios" es compartida:
--   authService la crea al hacer login con Firebase
--   userService la lee/actualiza (perfil, avatar)
--   orderService la referencia (user_id en orders)
-- El ID es el Firebase UID (String), NO autoincremental.
-- ============================================

CREATE TABLE usuarios (
    id              VARCHAR(255)    NOT NULL,
    email           VARCHAR(255)    NOT NULL,
    nombre          VARCHAR(255)    NOT NULL,
    fecha_nacimiento DATE,
    avatar_url      VARCHAR(255),
    activo          BOOLEAN         NOT NULL DEFAULT TRUE,
    creado_en       TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    actualizado_en  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    rol             VARCHAR(255)    NOT NULL DEFAULT 'USER',

    CONSTRAINT pk_usuarios PRIMARY KEY (id),
    CONSTRAINT uq_usuarios_email UNIQUE (email)
);

-- ============================================
-- AUTH SERVICE
-- ============================================
-- Sesiones de refresh token. El ID es UUID generado en @PrePersist.
-- ============================================

CREATE TABLE auth_sessions (
    id              UUID            NOT NULL,
    user_id         VARCHAR(255)    NOT NULL,
    refresh_token   VARCHAR(255)    NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    expires_at      TIMESTAMPTZ     NOT NULL,
    revoked         BOOLEAN         NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_auth_sessions PRIMARY KEY (id)
);

-- ============================================
-- USER SERVICE
-- ============================================
-- Direcciones de envio de los usuarios.
-- usuario_id referencia a usuarios.id (Firebase UID).
-- ============================================

CREATE TABLE direcciones (
    id              BIGSERIAL       NOT NULL,
    alias           VARCHAR(255),
    calle           VARCHAR(255)    NOT NULL,
    numero          VARCHAR(255)    NOT NULL,
    depto           VARCHAR(255),
    ciudad          VARCHAR(255)    NOT NULL,
    region          VARCHAR(255),
    pais            VARCHAR(255)    NOT NULL,
    usuario_id      VARCHAR(255)    NOT NULL,
    creado_en       TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    actualizado_en  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_direcciones PRIMARY KEY (id)
);

-- ============================================
-- PRODUCT SERVICE
-- ============================================
-- Catalogo de productos, especificaciones tecnicas y resenas.
-- Product.id es int con IDENTITY.
-- ============================================

CREATE TABLE products (
    id              INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    codigo          VARCHAR(255)    NOT NULL,
    nombre          VARCHAR(255)    NOT NULL,
    descripcion_corta VARCHAR(255)  NOT NULL,
    descripcion_larga TEXT          NOT NULL,
    categoria       VARCHAR(255)    NOT NULL,
    precio          DOUBLE PRECISION NOT NULL,
    stock           INTEGER         NOT NULL,
    imagen_url      VARCHAR(255)    NOT NULL,

    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT uq_products_codigo UNIQUE (codigo)
);

CREATE TABLE product_specifications (
    id              BIGSERIAL       NOT NULL,
    specification   VARCHAR(255)    NOT NULL,
    product_id      INTEGER,

    CONSTRAINT pk_product_specifications PRIMARY KEY (id)
);

CREATE TABLE resenas (
    id              BIGSERIAL       NOT NULL,
    comentario      TEXT            NOT NULL,
    puntuacion      INTEGER         NOT NULL,
    usuario_id      VARCHAR(255)    NOT NULL,
    created_at      TIMESTAMP,
    product_id      INTEGER         NOT NULL,

    CONSTRAINT pk_resenas PRIMARY KEY (id)
);

-- ============================================
-- CART SERVICE
-- ============================================
-- Carritos de compra. Soporta usuarios autenticados (user_id)
-- y anonimos/guest (session_id). Ambos son UNIQUE.
-- IDs son UUID generados por Hibernate (GenerationType.AUTO).
-- ============================================

CREATE TABLE carts (
    id              UUID            NOT NULL DEFAULT gen_random_uuid(),
    user_id         VARCHAR(255),
    session_id      VARCHAR(255),
    updated_at      TIMESTAMP,

    CONSTRAINT pk_carts PRIMARY KEY (id),
    CONSTRAINT uq_carts_user_id UNIQUE (user_id),
    CONSTRAINT uq_carts_session_id UNIQUE (session_id)
);

CREATE TABLE cart_items (
    id              UUID            NOT NULL DEFAULT gen_random_uuid(),
    cart_id         UUID            NOT NULL,
    product_id      VARCHAR(255)    NOT NULL,
    product_name    VARCHAR(255)    NOT NULL,
    unit_price      BIGINT          NOT NULL,
    quantity        INTEGER         NOT NULL,
    imagenurl       VARCHAR(255),

    CONSTRAINT pk_cart_items PRIMARY KEY (id)
);

-- ============================================
-- ORDER SERVICE
-- ============================================
-- Ordenes de compra y sus items.
-- Incluye logica de puntos y descuentos.
-- IDs son UUID generados por Hibernate (GenerationType.AUTO).
-- ============================================

CREATE TABLE orders (
    id                      UUID        NOT NULL DEFAULT gen_random_uuid(),
    user_id                 VARCHAR(100) NOT NULL,
    created_at              TIMESTAMP   NOT NULL,
    total_amount            BIGINT      NOT NULL,
    discount_percent        INTEGER     NOT NULL,
    final_amount            BIGINT      NOT NULL,
    points_granted          BIGINT      NOT NULL,
    points_spent            BIGINT      NOT NULL,
    used_points_discount    BOOLEAN     NOT NULL DEFAULT FALSE,
    used_email_discount     BOOLEAN     NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE order_items (
    id              UUID            NOT NULL DEFAULT gen_random_uuid(),
    product_id      VARCHAR(50)     NOT NULL,
    product_name    VARCHAR(255)    NOT NULL,
    image           VARCHAR(500),
    price           BIGINT          NOT NULL,
    quantity        INTEGER         NOT NULL,
    order_id        UUID            NOT NULL,

    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

-- ============================================
-- FOREIGN KEYS
-- ============================================

-- auth_sessions.user_id -> usuarios.id
ALTER TABLE auth_sessions
    ADD CONSTRAINT fk_auth_sessions_usuario
    FOREIGN KEY (user_id) REFERENCES usuarios(id);

-- direcciones.usuario_id -> usuarios.id
ALTER TABLE direcciones
    ADD CONSTRAINT fk_direcciones_usuario
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id);

-- product_specifications.product_id -> products.id
ALTER TABLE product_specifications
    ADD CONSTRAINT fk_product_specifications_product
    FOREIGN KEY (product_id) REFERENCES products(id);

-- resenas.product_id -> products.id
ALTER TABLE resenas
    ADD CONSTRAINT fk_resenas_product
    FOREIGN KEY (product_id) REFERENCES products(id);

-- resenas.usuario_id -> usuarios.id
ALTER TABLE resenas
    ADD CONSTRAINT fk_resenas_usuario
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id);

-- cart_items.cart_id -> carts.id
ALTER TABLE cart_items
    ADD CONSTRAINT fk_cart_items_cart
    FOREIGN KEY (cart_id) REFERENCES carts(id);

-- order_items.order_id -> orders.id
ALTER TABLE order_items
    ADD CONSTRAINT fk_order_items_order
    FOREIGN KEY (order_id) REFERENCES orders(id);

-- ============================================
-- INDICES
-- ============================================

-- Auth sessions: busqueda por user_id y por token
CREATE INDEX idx_auth_sessions_user_id ON auth_sessions(user_id);
CREATE INDEX idx_auth_sessions_refresh_token ON auth_sessions(refresh_token);

-- Direcciones: busqueda por usuario
CREATE INDEX idx_direcciones_usuario_id ON direcciones(usuario_id);

-- Products: busqueda por categoria
CREATE INDEX idx_products_categoria ON products(categoria);

-- Resenas: busqueda por producto y usuario
CREATE INDEX idx_resenas_product_id ON resenas(product_id);
CREATE INDEX idx_resenas_usuario_id ON resenas(usuario_id);

-- Product specifications: busqueda por producto
CREATE INDEX idx_product_specifications_product_id ON product_specifications(product_id);

-- Cart items: busqueda por carrito
CREATE INDEX idx_cart_items_cart_id ON cart_items(cart_id);

-- Orders: busqueda por usuario
CREATE INDEX idx_orders_user_id ON orders(user_id);

-- Order items: busqueda por orden
CREATE INDEX idx_order_items_order_id ON order_items(order_id);

-- ============================================
-- FIN DEL SCRIPT
-- ============================================
-- Tablas creadas: 10
-- Para verificar: \dt
-- ============================================
